### ISSUE TITLE
feature request: move a frame between workspaces

### ISSUE THREAD

**Issue by articuluxe** [wasamasa/eyebrowse#45]
I think it would be a killer feature to be able to move or clone a frame into a different workspace.  If this functionality is already there, I missed it.

In any event, thank you for eyebrows, it is very useful!

**Comment by wasamasa** [comment]
Are you sure it's not the other way around?

A frame holds a list of window configurations, so moving a window configuration from one frame to another one would be possible.  Same goes for moving a window configuration from one slot to another one.  But transplanting a frame between workspaces?

**Comment by danrharms** [comment]
Yes  :)

The corollary would be in virtual desktop managers e.g. kde or gnome.  That is, the ability to transfer one element (i.e. window in OS parlance) of a workspace into another.

The usefulness comes when sometimes, after you have correctly partitioned out your work among different workspaces so that unrelated items do not collide, you find that e.g. a piece of data or code needs to be transferred between projects or workspaces.  Then it becomes useful to move a window into another workspace, so that you do not need to replicate it by hand in the target workspace.

A second use-case arises when you simply make a mistake, and create a window in the wrong workspace to begin with.

In emacs terms, even though transferring a window satisfies the use case, you still need a frame to transfer it into, so I thought that moving or cloning a frame would be the closest use case.  Even though technically we don't care about the frame per se, only the content (i.e. buffer(s)) of the contained windows.

I realize it may not be easy, it is just to me an important part of trying to use emacs (with eyebrowse's interface) as its own window manager.

**Comment by wasamasa** [comment]
So you would like to have commands for sending a window to an existing
workspace, sending a window to a new workspace and sending a window to a
workspace on another frame, even if that frame doesn't exist yet?

**Comment by danrharms** [comment]
1. 
> sending a window to an existing
> workspace
This is the most useful. Though I would say Copying rather than Cloning, probably more useful in the general case. 

2. 
> sending a window to a new workspace 
Not as useful, as can be accomplished by existing eyebrows commands, if I'm not mistaken. 

3.
> sending a window to a
> workspace on another frame, even if that frame doesn't exist yet

Hmm, I don't know. I think this would make more sense if workspaces could have multiple frames, which is what I originally thought. Otherwise, it doesn't seem too useful. 

If you don't think these are useful to people, that's all right, I just thought they might be. Thanks for your attention.
