### ISSUE TITLE
bug/feature req: When burying a buffer in a window-config, the 'last' buffer (top of buffer stack) is not preserved per config.

### ISSUE THREAD

**Issue by ahungry** [wasamasa/eyebrowse#72]
Steps:

1. Start a window-config, with a file open.
2. Start a new window-config and do something like `M-x hackernews`, then follow an article to it's eww buffer (at this point, the non-visible buffer stack has the *hackernews* buffer on top)
3. Go back to window-config 1 and open a second file (hence pushing the first open file to the top of the buffer stack/list)
4. Jump back to window-config 2 and press 'q' to bury the eww buffer - at this point, it would be expected that the *hackernews* buffer was visible, but unfortunately the file from step 1 is

Is there any way to have each window-config track its own buffer stack / sort order?

**Comment by wasamasa** [comment]
No and this is out of scope for this package.

**Comment by jernejkase** [comment]
Then this package is not a proper window manager like i3

**Comment by wasamasa** [comment]
I'm not sure why you expect it to be. At no point the README suggests it provides a window manager for Emacs. This package is closer to saving/restoring window configurations manually with `C-x r w` than being i3.

**Comment by novoid** [comment]
I understand that this feature request was not in the mind of the author or a goal to achieve.

However, this feature would be very helpful for my use-case as well.

Do you think that this could be achieved by some `(add-to-list 'window-persistent-parameters '(FOO-BAR . writable))` magic (which I do not understand yet)?

I'd love to stick with eyebrowse instead of switching to something more sophisticated (and more complicated) just for the sake of storing and restoring the current stack of buffers order in addition to the current window/buffer only ...

**Comment by wasamasa** [comment]
If it were that simple, I'd have done it in the first place. Take a look at `(info "(elisp) Window Parameters")` for yourself, you'll find it's about window-specific properties, not something as global as the buffer list.
